/*
 * File: z_mc_skyline.c
 * Overlay: ovl_Mc_Skyline
 * Description: Majora City procedural skyline. Draws a ring of Art Deco skyscrapers around the Clock Tower.
 *
 * The geometry and window textures are generated by tools/gen_skyline.py (mc_skyline_data.inc.c), so the
 * overlay carries all of its own data and depends on no object file. One 32x32 I8 texture is shared by every
 * tower; per-tower variety comes from archetype, scale, yaw and a primitive-colour "tone". The skyline is
 * tinted by time of day and switches to a lit-windows texture at night.
 *
 * Params: McSkylineLayout (0 = Termina Field, 1 = Old Town).
 */

#include "z_mc_skyline.h"

#define FLAGS (ACTOR_FLAG_UPDATE_CULLING_DISABLED | ACTOR_FLAG_DRAW_CULLING_DISABLED)

// How far below the reference height towers start, so uneven ground never shows a gap under them.
#define MC_SKYLINE_FIELD_SINK 200.0f
#define MC_SKYLINE_TOWN_SINK 800.0f

// Frames to wait for the Clock Tower actor before falling back to the spawn position as the centre.
#define MC_SKYLINE_SEARCH_FRAMES 10

void McSkyline_Init(Actor* thisx, PlayState* play);
void McSkyline_Destroy(Actor* thisx, PlayState* play);
void McSkyline_Update(Actor* thisx, PlayState* play);
void McSkyline_Draw(Actor* thisx, PlayState* play);

ActorProfile Mc_Skyline_Profile = {
    /**/ ACTOR_MC_SKYLINE,
    /**/ ACTORCAT_PROP,
    /**/ FLAGS,
    /**/ GAMEPLAY_KEEP,
    /**/ sizeof(McSkyline),
    /**/ McSkyline_Init,
    /**/ McSkyline_Destroy,
    /**/ McSkyline_Update,
    /**/ McSkyline_Draw,
};

#include "mc_skyline_data.inc.c"

// Facade materials, multiplied with the time-of-day tint. tools/preview_skyline.py reads this table too.
static Color_RGB8 sMcSkylineTones[] = {
    { 232, 208, 168 }, // Sandstone
    { 226, 224, 214 }, // Limestone
    { 214, 150, 120 }, // Terracotta
    { 160, 172, 190 }, // Slate
    { 150, 200, 180 }, // Verdigris
    { 245, 232, 200 }, // Cream
};

typedef struct McSkylineLayoutInfo {
    /* 0x0 */ McSkylineTower* towers;
    /* 0x4 */ s16 count;
    /* 0x8 */ f32 sink;
} McSkylineLayoutInfo; // size = 0xC

static McSkylineLayoutInfo sMcSkylineLayouts[MC_SKYLINE_LAYOUT_MAX] = {
    { sMcSkylineLayoutField, ARRAY_COUNT(sMcSkylineLayoutField), MC_SKYLINE_FIELD_SINK }, // MC_SKYLINE_LAYOUT_FIELD
    { sMcSkylineLayoutTown, ARRAY_COUNT(sMcSkylineLayoutTown), MC_SKYLINE_TOWN_SINK },    // MC_SKYLINE_LAYOUT_TOWN
};

void McSkyline_Init(Actor* thisx, PlayState* play) {
    McSkyline* this = (McSkyline*)thisx;
    s32 layout = MC_SKYLINE_GET_LAYOUT(&this->actor);

    if ((layout >= MC_SKYLINE_LAYOUT_MAX) || (sMcSkylineLayouts[layout].count > MC_SKYLINE_MAX_TOWERS)) {
        Actor_Kill(&this->actor);
        return;
    }

    // Survive room changes: the skyline belongs to the whole scene.
    this->actor.room = -1;
    this->towers = sMcSkylineLayouts[layout].towers;
    this->towerCount = sMcSkylineLayouts[layout].count;
    this->center = this->actor.home.pos;
    this->searchTimer = MC_SKYLINE_SEARCH_FRAMES;
    this->state = MC_SKYLINE_STATE_FIND_CENTER;
}

void McSkyline_Destroy(Actor* thisx, PlayState* play) {
}

static void McSkyline_PlaceTowers(McSkyline* this) {
    s32 layout = MC_SKYLINE_GET_LAYOUT(&this->actor);
    f32 baseY;
    s32 i;

    if (layout == MC_SKYLINE_LAYOUT_TOWN) {
        // The Clock Tower actor in town is the clock face, high on the tower; the spawn height is street level.
        baseY = this->actor.home.pos.y;
    } else {
        baseY = this->center.y;
    }
    baseY -= sMcSkylineLayouts[layout].sink;

    for (i = 0; i < this->towerCount; i++) {
        McSkylineTower* tower = &this->towers[i];

        this->towerPos[i].x = this->center.x + Math_SinS(tower->angle) * tower->radius;
        this->towerPos[i].y = baseY;
        this->towerPos[i].z = this->center.z + Math_CosS(tower->angle) * tower->radius;
    }
}

void McSkyline_Update(Actor* thisx, PlayState* play) {
    McSkyline* this = (McSkyline*)thisx;

    if (this->state == MC_SKYLINE_STATE_FIND_CENTER) {
        this->searchTimer--;
        if (McCore_FindCityCenter(play, &this->center) || (this->searchTimer <= 0)) {
            McSkyline_PlaceTowers(this);
            this->state = MC_SKYLINE_STATE_READY;
        }
    }
}

/**
 * Chooses the window texture and the light tint for the current time of day.
 */
static void* McSkyline_GetLook(Color_RGB8* tint) {
    u16 time = CURRENT_TIME;

    if ((time >= CLOCK_TIME(19, 0)) || (time < CLOCK_TIME(5, 0))) {
        // Night: dark facades, lit offices.
        tint->r = 255;
        tint->g = 225;
        tint->b = 170;
        return sMcSkylineWindowNightTex;
    }

    if (time < CLOCK_TIME(6, 30)) {
        // Dawn
        tint->r = 255;
        tint->g = 200;
        tint->b = 160;
    } else if (time < CLOCK_TIME(17, 0)) {
        // Day
        tint->r = 255;
        tint->g = 255;
        tint->b = 255;
    } else {
        // Dusk
        tint->r = 255;
        tint->g = 190;
        tint->b = 150;
    }
    return sMcSkylineWindowDayTex;
}

void McSkyline_Draw(Actor* thisx, PlayState* play) {
    McSkyline* this = (McSkyline*)thisx;
    Color_RGB8 tint;
    void* texture;
    s32 i;

    if (this->state != MC_SKYLINE_STATE_READY) {
        return;
    }

    texture = McSkyline_GetLook(&tint);

    OPEN_DISPS(play->state.gfxCtx);

    // Two-cycle, fogged, opaque; lighting off so the baked vertex shading is used as colour.
    Gfx_SetupDL25_Opa(play->state.gfxCtx);
    gSPLoadGeometryMode(POLY_OPA_DISP++, G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_SHADING_SMOOTH);
    // Cycle 1: window texture * vertex shade. Cycle 2: * primitive (tower tone x time-of-day tint).
    gDPSetCombineLERP(POLY_OPA_DISP++, TEXEL0, 0, SHADE, 0, 0, 0, 0, 1, COMBINED, 0, PRIMITIVE, 0, 0, 0, 0, 1);
    gSPTexture(POLY_OPA_DISP++, 0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON);
    gDPLoadTextureBlock(POLY_OPA_DISP++, texture, G_IM_FMT_I, G_IM_SIZ_8b, 32, 32, 0, G_TX_NOMIRROR | G_TX_WRAP,
                        G_TX_NOMIRROR | G_TX_WRAP, 5, 5, G_TX_NOLOD, G_TX_NOLOD);

    for (i = 0; i < this->towerCount; i++) {
        McSkylineTower* tower = &this->towers[i];
        Color_RGB8* tone = &sMcSkylineTones[tower->tone];
        f32 scaleXZ = tower->scaleXZ * 0.01f;

        Matrix_Translate(this->towerPos[i].x, this->towerPos[i].y, this->towerPos[i].z, MTXMODE_NEW);
        Matrix_RotateYS(tower->yaw, MTXMODE_APPLY);
        Matrix_Scale(scaleXZ, tower->scaleY * 0.01f, scaleXZ, MTXMODE_APPLY);
        MATRIX_FINALIZE_AND_LOAD(POLY_OPA_DISP++, play->state.gfxCtx);

        gDPSetPrimColor(POLY_OPA_DISP++, 0, 0xFF, (tone->r * tint.r) / 255, (tone->g * tint.g) / 255,
                        (tone->b * tint.b) / 255, 255);
        gSPDisplayList(POLY_OPA_DISP++, sMcSkylineArchetypeDLs[tower->archetype]);
    }

    CLOSE_DISPS(play->state.gfxCtx);
}
